name: issue-notify

on:
  issues:
    types: [opened]

jobs:
  get-keyword:
    runs-on: ubuntu-latest
    outputs:
      level: ${{ steps.get-keyword.outputs.level }}

    steps:
      - uses: actions/checkout@v4

      - name: get keyword
        id: get-keyword
        shell: bash
        run: |
          echo "level=Undefined" >> "$GITHUB_OUTPUT"

          title="${{ github.event.issue.title }}"
          echo "Issue Title: $title"

          while IFS= read -r keyword; do
            [[ -z "$keyword" || "$keyword" =~ ^# ]] && continue
            if [[ "$title" =~ $keyword ]]; then
              echo "match: $keyword"
              echo "level=$keyword" >> "$GITHUB_OUTPUT"
              break
            fi
          done < keyword-list.txt

      - name: get output
        run: echo "LEVEL=${{ steps.get-keyword.outputs.level }}"

  slack:
    needs: [get-keyword]
    if: ${{ needs.get-keyword.outputs.level != 'Undefined' }}
    runs-on: ubuntu-latest
    environment: ${{ needs.get-keyword.outputs.level }}   # 환경 이름이 실제로 존재해야 함
    steps:
      - name: slack
        uses: slackapi/slack-github-action@v2.1.1
        with:
          payload: |
            {
              "attachments": [
                {
                  "pretext": "issue alert message",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "level: ${{ needs.get-keyword.outputs.level }}",
                      "short": true,
                      "value": "issue url : ${{ github.event.issue.html_url }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
