name: environment

on: push

jobs:
  get-env:
    runs-on: ubuntu-latest
    env: 
      LEVEL: ${{ vars.LEVEL }}
      KEY: ${{ secrets.KEY }}
    
    steps:
      - name: check env & secret
        run: |
          echo "LEVEL=$LEVEL"
          echo "KEY=$KEY"

  get-env-dev:
    runs-on: ubuntu-latest
    steps:
      - name: check env & secret
        run: |
          echo ${{ vars.LEVEL }}
          echo ${{ secrets.KEY }}