name: environment

on: push

jobs:
  get-env:
    runs-on: ubuntu-latest
    
    steps:
      - name: check env & secret update
        run: |
          echo ${{ vars.LEVEL }}
          echo ${{ secrets.KEY }}
    # env: 
    #   LEVEL: ${{ vars.LEVEL }}
    #   KEY: ${{ secrets.KEY }}

  # get-env-dev:
  #   runs-on: ubuntu-latest
  #   environment: dev
  #   steps:
  #     - name: check env & secret
  #       run: |
  #         echo "LEVEL=$LEVEL"
  #         echo "KEY=$KEY"