name: environment

on: push

jobs:
  get-env:
    runs-on: ubuntu-latest
    
    steps:
      - name: check env & secret org
        run: |
          echo "LEVEL: ${{ vars.level }}"
          echo "KEY: ${{ secrets.key }}"

  get-env-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: check env & secret
        run: |
          echo "LEVEL: ${{ vars.level }}"
          echo "KEY: ${{ secrets.key }}"
