name: issue-notify

on:
  issues:
    types: [opened]

jobs:
  get-keyword:
    runs-on: ubuntu-latest
    outputs:
      level: ${{ steps.get-keyword.outputs.level }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: get keyword
        id: get-keyword
        run: |
          echo level=Undefined >> $GITHUB_OUTPUT

          title="${{ github.event.issue.title }}"
          echo "Issue Title : $title"
          
          keywords=$(cat keyword-list.txt)

          for keyword in $keywords; do

          if [["$title"=~ $keyword]]; then
            echo match: $keyword
            echo "level=$keyword" >> $GITHUB_OUTPUT

          fi

          done
      - name: get output
        run: |
          echo ${{ steps.get-keyword.outputs.level}}